# flake8: noqa

"""
    Feiertage API

    Deutsche Feiertage per JSON-Webservice (API)   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.1"

# import ApiClient
from deutschland.feiertage.api_client import ApiClient

# import Configuration
from deutschland.feiertage.configuration import Configuration

# import exceptions
from deutschland.feiertage.exceptions import (
    ApiAttributeError,
    ApiException,
    ApiKeyError,
    ApiTypeError,
    ApiValueError,
    OpenApiException,
)
