"""
    Feiertage API

    Deutsche Feiertage per JSON-Webservice (API)   # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""

import sys
import unittest

from deutschland.feiertage.model.feiertag import Feiertag

from deutschland import feiertage


class TestFeiertag(unittest.TestCase):
    """Feiertag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeiertag(self):
        """Test Feiertag"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Feiertag()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
